homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_tz
  # customize display of components
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml


# Show links to resources in log and frontend
# introduction:

# Example configuration.yaml entry
notify:
  - name: mail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret mail_sender
    encryption: starttls
    username: !secret mail_sender
    password: !secret mail_password
    recipient: !secret mail_recipient

# Enables the frontend
frontend:

switch:
  - platform: flux
    lights:
      - light.living_room_overhead
      - light.couch_corner
      - light.bedroom
    name: Fluxer
    start_time: '06:30'
    stop_time: '23:00'
    start_colortemp: 3500
    sunset_colortemp: 2750
    stop_colortemp: 2500
    disable_brightness_adjust: True
    mode: mired

tplink:
  discovery: false
  switch:
    - host: !secret guest_bedroom_tplink_ip
    - host: !secret living_room_tplink_ip

http:
  server_port: !secret server_port
  ssl_certificate: !secret server_certificate
  ssl_key: !secret server_key

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_keep_days: 10
  purge_interval: 1

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - nearest_storm_distance

binary_sensor:
  - platform: flic
    discovery: false

# Enable the configuration panel
config:

# open zwave
zwave:
    usb_path: /dev/zwave
    polling_interval: 5000
    network_key: !secret zwave_network_key
    device_config: !include zwave_device_config.yaml

mqtt:
    broker: localhost
    port: !secret mqtt_port
    client_id: home-assistant-1
    keepalive: 60
    protocol: 3.1
    username: !secret mqtt_username
    password: !secret mqtt_password
    discovery: true
    discovery_prefix: homeassistant
    birth_message:
      topic: 'hass/status'
      payload: 'online'
    will_message:
      topic: 'hass/status'
      payload: 'offline'


device_tracker:
  - platform: owntracks
    track_new_devices: no
  - platform: snmp
    host: !secret router_ip
    community: !secret snmp_community
    baseoid: !secret snmp_baseoid
  - platform: unifi
    host: !secret unifi_ip
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: !secret unifi_ca
    ssid_filter:
      - !secret unifi_ssid

wake_on_lan:

# Example configuration.yaml entry
media_player:
  - platform: kodi
    host: !secret kodi_ip
    username: !secret kodi_username
    password: !secret kodi_password
  - platform: denon
    host: !secret denon_ip
    name: Denon
  - platform: webostv
    host: !secret tv_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac
    customize:
      sources:
        - hdmi2
        - netflix
        - hulu
        - livetv
        - youtube

# Example configuration.yaml entry
ecobee:
  api_key: !secret ecobee_api_key

  #hue:
  #  bridges:
  #    - host: !secret hue_ip

lifx:
  light:

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

# Add custom zones
zone 1:
  name: AprilWork
  latitude: !secret april_work_lat
  longitude: !secret april_work_lon
  icon: mdi:lightbulb-on

zone 2:
  name: KitWork
  latitude: !secret kit_work_lat
  longitude: !secret kit_work_lon
  icon: mdi:fire

zone 3:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  radius: 100
  icon: mdi:home

logger:
  default: warn
  #logs:
    #homeassistant.core: debug
    #homeassistant.components.zwave: debug
    #homeassistant.components.binary_sensor.flic: debug
    #homeassistant.components.switch.flux: info

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.all_lights
      - switch.living_room_switch
      - switch.office_switch
      - switch.bathroom_switch
      - switch.guest_bathroom_switch
      - switch.dining_room_light
      - switch.guest_bedroom_lamp
      - switch.kitchen_switch
      - device_tracker.april_android
      - device_tracker.kit_android
      - binary_sensor.living_room_occupancy
      - binary_sensor.my_ecobee_occupancy
      - binary_sensor.guest_bedroom_occupancy
      - binary_sensor.bedroom_occupancy
      - sensor.living_room_temperature
      - sensor.my_ecobeex_humidity
      - sensor.dark_sky_summary
      - media_player.kodi
      - media_player.denon_avr_x2000
      - media_player.lg_webos_smart_tv
      - climate.my_ecobee
      - weather.my_ecobee
  living_room:
    name: Living Room
    icon: mdi:sofa
    view: yes
    entities:
      - light.couch_corner
      - light.desk
      - light.living_room_overhead
      - switch.dining_room_light
      - switch.living_room_switch
  ipcamera:
    name: Camera
    view: yes
    icon: mdi:cctv
    entities:
      - camera.kitchen
      - switch.dafang_h264_rtsp_server
      - switch.dafang_mjpeg_rtsp_server
      - sensor.dafang
      - device_tracker.dafang3
      - sensor.dafang_light_sensor
      - switch.dafang_ir_filter
      - switch.dafang_ir_led
      - switch.dafang_night_mode
      - switch.dafang_night_mode_auto
      - switch.dafang_blue_led
      - switch.dafang_yellow_led
      - switch.dafang_motion_detection
      - switch.dafang_motion_tracking
      - camera.dafang_motion_snapshot
      - binary_sensor.dafang_motion_sensor
      - cover.dafang_move_leftright
      - cover.dafang_move_updown

scene:
  - name: Movie
    entities:
      light.couch_corner:
        state: on
        transition: 1
        brightness: 50
        kelvin: 2700
        white_value: 255
      light.living_room_overhead:
        state: on
        transition: 1
        brightness: 1
        kelvin: 2700
        white_value: 255
      switch.dining_room_light:
        state: off
  - name: Bedroom Day
    entities:
      light.bedroom:
        state: on
        transition: 1
        brightness: 255
        kelvin: 3003
        white_value: 255
  - name: Guest Bedroom Day
    entities:
      light.guest_bedside_table:
        state: on
        transition: 1
        brightness: 255
        kelvin: 3003
        white_value: 255
      switch.guest_bedroom_lamp:
        state: on
  - name: Bedroom Dim
    entities:
      light.bedroom:
        state: on
        transition: 1
        brightness: 55
        kelvin: 3003
        white_value: 255
  - name: Guest Bedroom Dim
    entities:
      light.guest_bedside_table:
        state: on
        transition: 1
        brightness: 55
        kelvin: 3003
        white_value: 255
      switch.guest_bedroom_lamp:
        state: on
  - name: Bedroom Night
    entities:
      light.bedroom:
        state: on
        transition: 1
        brightness: 200
        kelvin: 2700
        white_value: 255
  - name: Guest Bedroom Night
    entities:
      light.guest_bedside_table:
        state: on
        transition: 1
        brightness: 200
        kelvin: 2700
        white_value: 255
      switch.guest_bedroom_lamp:
        state: on
  - name: Living Room Off
    entities:
      light.living_room_overhead:
        state: off
        transition: 0
      light.couch_corner:
        state: off
        transition: 0
  - name: Living Room On
    entities:
      light.living_room_overhead:
        state: on
        transition: 1
        brightness: 255
        kelvin: 2700
        white_value: 255
      light.couch_corner:
        state: on
        transition: 1
        brightness: 153
        kelvin: 2777
        white_value: 255
  - name: Office On
    entities:
      light.desk:
        state: on
      switch.dining_room_light:
        state: on
  - name: Office Off
    entities:
      light.desk:
        state: off
      switch.dining_room_light:
        state: off
      light.desk:
        state: off
  - name: Kitchen On
    entities:
      light.kitchen_range:
        state: on
        brightness: 255
        kelvin: 3154
        transition: 0
  - name: Kitchen Relax
    entities:
      switch.kitchen_switch:
        state: on
      light.kitchen_range:
        state: off
        transition: 0
  - name: Kitchen Range
    entities:
      switch.kitchen_switch:
        state: off
      light.kitchen_range:
        state: on
        transition: 0
        brightness: 255
        kelvin: 3154
  - name: Kitchen Off
    entities:
      light.kitchen_range:
        state: off
        transition: 0
  - name: Main Room Relax
    entities:
      light.couch_corner:
        state: on
        transition: 1
        brightness: 255
        kelvin: 2700
        white_value: 255
      light.living_room_overhead:
        state: on
        transition: 1
        brightness: 75
        kelvin: 2700
        white_value: 255
      switch.dining_room_light:
        state: off
  - name: Desk
    entities:
      light.desk:
        state: on
        transition: 2
        brightness: 255
        kelvin: 2700
        white_value: 127

input_boolean:
  someonehome:
    name: Someone home
    initial: on
    icon: mdi:cellphone-iphone

light:
  - name: bedroom_headboard
    platform: mqtt
    state_topic: ESPURNA-6F9708/relay/0
    command_topic: ESPURNA-6F9708/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: ESPURNA-6F9708/status
    payload_available: 1
    payload_not_available: 0
    brightness_state_topic: ESPURNA-6F9708/brightness
    brightness_command_topic: ESPURNA-6F9708/brightness/set
    rgb_state_topic: ESPURNA-6F9708/rgb
    rgb_command_topic: ESPURNA-6F9708/rgb/set
    color_temp_command_topic: ESPURNA-6F9708/mired/set
    white_value_state_topic: ESPURNA-6F9708/channel/3
    white_value_command_topic: ESPURNA-6F9708/channel/3/set

automation: !include automations.yaml
camera: !include cameras.yaml
script: !include scripts.yaml
